version: "3.9"

# Try `docker-compose up`

services:
    wg_proxy:
        image: jspantheonlab/wireguard-proxy
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        privileged: true
        volumes:
            - ./config/:/config/
        environment: # This needs to change - your local network
            - LOCAL_NETWORK=10.0.8.1/24
            # Create a .env file with these values
            # Adjust for your needs
            - WG_TUNNEL_HOSTS=*.openai.com
        ports:
            - 44081:80
            - 8080:8080
        restart: always
