#!/bin/sh

ifname=$(basename $(ls -1 ${WG_CONFIG}/*.conf | head -1) .conf)

ifpath=${WG_CONFIG}/$ifname.conf

if [ ! -f "${ifpath}" ] ; then
    echo "No Wireguard config. Exiting."
    exit 1
fi

function cleanup()
{
    echo "stopping wg interface..."
    wg-quick down ${wgConfigPath} || true
}
trap cleanup INT HUP SIGINT

oldip=$(curl -s ifconfig.me)

echo "starting wg interface..."
sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
wg-quick up ${ifpath}
wg show

echo "Regular IP: ${oldip}"

newip=$(curl -s ifconfig.me) 
echo "Wireguard IP: ${newip}"

sleep infinity &
wait

