#!/bin/sh

if [ -z ${LOCAL_NETWORK} ]; then
    echo "Please set LOCAL_NETWORK environment variable."
    exit 1
fi

sleep 5

export TEMP_DIR="$(mktemp -d)"



DROUTE=$(ip route | grep default | awk '{print $3}')
HOMENET=192.168.0.0/16
HOMENET2=10.0.0.0/8
HOMENET3=172.16.0.0/12
ip route add $HOMENET3 via $DROUTE
ip route add $HOMENET2 via $DROUTE
ip route add $HOMENET via $DROUTE

echo "Adding routes to $HOMENET, $HOMENET2, $HOMENET3 via $DROUTE"

# add local ip to env SELF_IP
SELF_IP=$(ip addr show dev eth0 | grep -w inet | awk '{print $2}' | cut -d/ -f1)
echo "SELF_IP: $SELF_IP"
export SELF_IP

envsubst </app/privoxy/config >"${TEMP_DIR}/config"

# so return traffic that went through VPN works
# gw=$(ip route | awk '/default/ {print $3}')
# echo $gw
# ip route add to ${LOCAL_NETWORK} via $gw dev eth0

# start
privoxy --no-daemon "${TEMP_DIR}/config"
